version: '2'

services:
  crawler_compare:
    image: joeblade/crawler:1.0-SNAPSHOT
    volumes:
      - crawler_data:/crawler_result
      - crawler_work:/crawler_worky
    environment:
      crawler.startPage: "http://sys4.open-web.nl:8880/site/"
      crawler.siteBaseUrl: "http://sys4.open-web.nl:8880/site/"
      crawler.comparePath: "http://sys4.open-web.nl:8880/site/"
      spring.datasource.url: "jdbc:mysql://database/dbName"
      spring.datasource.username: "username"
      spring.datasource.password: "userPassword"
      spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
      spring.jpa.hibernate.ddl-auto: "none"
    command: java -jar app.jar compare
    networks:
      - crawler_app_network
volumes:
  crawler_data:
    driver: local
  crawler_work:
    driver: local
networks:
  crawler_app_network:
    external: true