version: '2'

services:
  crawler_compare:
    image: aharpour/crawler-2:1.0-SNAPSHOT
    volumes:
      - crawler_data:/crawler_result
      - crawler_work:/crawler_work
      - crawler_compare_result:/crawler_compare_result
      - crawler_diff:/crawler_diff
    environment:
      crawler.startPage: "http://localhost:8090/site/"
      crawler.siteBaseUrl: "http://localhost:8080/site/"
      crawler.comparePath: "http://localhost:8090/site/"
      crawler.concurrentThreads: 5
      spring.datasource.url: "jdbc:mysql://database/crawl"
      spring.datasource.username: "username"
      spring.datasource.password: "userPassword"
      spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
      spring.jpa.hibernate.ddl-auto: "none"
    command: java -jar app.jar compare
    networks:
      - crawler_app_network
volumes:
  crawler_data:
    driver: local
  crawler_work:
    driver: local
  crawler_compare_result:
    driver: local
  crawler_diff:
    driver: local
networks:
  crawler_app_network:
    external: true